version: "3.8"
services:
  app:
    container_name: golang
    build:
      context: "./app"
      dockerfile: Dockerfile
    image: "app-golang:1.0.0"
    environment:
      - "APP_PORT:8080"
    ports:
      - "8080:8080"
