version: "3.8"

services:
  mongodb-example:
    container_name: mongodb-example
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prinaf
      - MONGO_INITDB_ROOT_PASSWORD=prinaf
      - MONGO_INITDB_DATABASE=testing-db-docker
